parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"NlgY":[function(require,module,exports) {
function n(n){return"function"==typeof n}module.exports=function r(t,o,e){if("function"!=typeof t)throw new Error("reducer must be function");if([o,e].every(function(r){return n(r)}))throw new Error("can be only one store extension as function");if(n(o)&&void 0===e){return o(r,t,void 0)}var u=t,i=u(o,{type:"INIT",payload:{}}),c=[];return{dispatch:function(n){if("function"==typeof n)throw new Error("action must be plane object");var r=i;if((i=u(i,n))===r)throw new Error("reducer must return copy of object");c.forEach(function(n){n(i)})},getState:function(){return i},subscribe:function(n){return c.push(n),function(){var r=c.indexOf(n);r>=0&&c.splice(r,1)}}}};
},{}],"yqyC":[function(require,module,exports) {
function r(r,t){var e=Object.keys(r);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(r);t&&(n=n.filter(function(t){return Object.getOwnPropertyDescriptor(r,t).enumerable})),e.push.apply(e,n)}return e}function t(t){for(var n=1;n<arguments.length;n++){var o=null!=arguments[n]?arguments[n]:{};n%2?r(o,!0).forEach(function(r){e(t,r,o[r])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(o)):r(o).forEach(function(r){Object.defineProperty(t,r,Object.getOwnPropertyDescriptor(o,r))})}return t}function e(r,t,e){return t in r?Object.defineProperty(r,t,{value:e,enumerable:!0,configurable:!0,writable:!0}):r[t]=e,r}function n(r){return c(r)||a(r)||o()}function o(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function a(r){if(Symbol.iterator in Object(r)||"[object Arguments]"===Object.prototype.toString.call(r))return Array.from(r)}function c(r){if(Array.isArray(r)){for(var t=0,e=new Array(r.length);t<r.length;t++)e[t]=r[t];return e}}function i(){for(var r=arguments.length,t=new Array(r),e=0;e<r;e++)t[e]=arguments[e];if(!t.length)throw new Error("no pass one middleware");return 1===t.length?t[0]:t.reduce(function(r,t){return function(){return r(t.apply(void 0,arguments))}})}module.exports=function(){for(var r=arguments.length,e=new Array(r),o=0;o<r;o++)e[o]=arguments[o];return function(r,o){for(var a=arguments.length,c=new Array(a>2?a-2:0),u=2;u<a;u++)c[u-2]=arguments[u];var f=r.apply(void 0,[o].concat(c)),p=function(){throw new Error("dispatch called too early")},l={getState:f.getState,dispatch:function(r){for(var t=arguments.length,e=new Array(t>1?t-1:0),n=1;n<t;n++)e[n-1]=arguments[n];return p.apply(void 0,[r].concat(e))}},y=e.map(function(r){return r(l)});return t({},f,{dispatch:p=i.apply(void 0,n(y))(f.dispatch)})}};
},{}],"4T3+":[function(require,module,exports) {
function t(){return function(t){var n=t.dispatch,r=t.getState;return function(t){return function(u){return"function"==typeof u?u(n,r):t(u)}}}}module.exports=t();
},{}],"Focm":[function(require,module,exports) {
var define;
var global = arguments[3];
var e,o=arguments[3];function t(e){return(t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}var n=require("./create_store"),r=require("./apply_middleware"),d=require("./function_middleware");!function(o){var u={createStore:n,applyMiddleware:r,middleware:d};"object"===("undefined"==typeof exports?"undefined":t(exports))&&"object"===("undefined"==typeof module?"undefined":t(module))?module.exports=u:"function"==typeof e&&e.amd?e([],func):"object"===("undefined"==typeof exports?"undefined":t(exports))&&(exports.redux=u),o.redux=u}("undefined"!=typeof window&&window||o);
},{"./create_store":"NlgY","./apply_middleware":"yqyC","./function_middleware":"4T3+"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map