parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"NlgY":[function(require,module,exports) {
"use strict";function r(r){return"function"==typeof r}function e(n,t,o){if("function"!=typeof n)throw new Error("reducer must be function");if([t,o].every(function(e){return r(e)}))throw new Error("can be only one store extension as function");if(r(t)&&void 0===o){return t(e,n,void 0)}var u=t,i=n,c=[];return{dispatch:function(r){var e=u;if((u=i(u,r))===e)throw new Error("reducer must return copy of object");c.forEach(function(r){r(u)})},getState:function(){return u},subscribe:function(r){return c.push(r),function(){var e=c.indexOf(r);e>=0&&c.splice(e,1)}}}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=e;
},{}],"yqyC":[function(require,module,exports) {
"use strict";function r(r){return e(r)||n(r)||t()}function t(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function n(r){if(Symbol.iterator in Object(r)||"[object Arguments]"===Object.prototype.toString.call(r))return Array.from(r)}function e(r){if(Array.isArray(r)){for(var t=0,n=new Array(r.length);t<r.length;t++)n[t]=r[t];return n}}function o(){for(var r=arguments.length,t=new Array(r),n=0;n<r;n++)t[n]=arguments[n];if(!t.length)throw new Error("no pass one middleware");return 1===t.length?t[0]:t.reduce(function(r,t){return function(){return r(t.apply(void 0,arguments))}})}function a(){for(var t=arguments.length,n=new Array(t),e=0;e<t;e++)n[e]=arguments[e];return function(t,e){for(var a=arguments.length,i=new Array(a>2?a-2:0),c=2;c<a;c++)i[c-2]=arguments[c];var u=t.apply(void 0,[e].concat(i)),l=function(){throw new Error("dispatch called too early")},f={getState:u.getState,dispatch:function(r){for(var t=arguments.length,n=new Array(t>1?t-1:0),e=1;e<t;e++)n[e-1]=arguments[e];return l.apply(void 0,[r].concat(n))}},p=n.map(function(r){return r(f)});return{store:u,dispatch:l=o.apply(void 0,r(p))(u.dispatch)}}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;
},{}],"4T3+":[function(require,module,exports) {
"use strict";function t(){return function(t){var e=t.dispatch,r=t.getState;return function(t){return function(n){return"function"==typeof n?n(e,r):t(n)}}}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t();exports.default=e;
},{}],"Focm":[function(require,module,exports) {
var define;
var global = arguments[3];
var e,o=arguments[3],t=u(require("./create_store")),n=u(require("./apply_middleware")),r=u(require("./function_middleware"));function u(e){return e&&e.__esModule?e:{default:e}}function d(e){return(d="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}!function(o){var u={createStore:t.default,applyMiddleware:n.default,middleware:r.default};"object"===("undefined"==typeof exports?"undefined":d(exports))&&"object"===("undefined"==typeof module?"undefined":d(module))?module.exports=u:"function"==typeof e&&e.amd?e([],func):"object"===("undefined"==typeof exports?"undefined":d(exports))&&(exports.redux=u),o.redux=u}("undefined"!=typeof window&&window||o);
},{"./create_store":"NlgY","./apply_middleware":"yqyC","./function_middleware":"4T3+"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map